version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        expose:
            - 5000
        environment:
           - PYTHONUNBUFFERED=1